# Generated by Django 2.0.3 on 2018-03-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='key',
            field=models.IntegerField(unique=True, verbose_name='Ключ'),
        ),
    ]
